import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { ArrowUpRight } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { PageHead } from "@/components/page-parts";
export const Route = createFileRoute("/contact")({ head: () => ({ meta: [{ title: "Contact Us | NeuronBridge Initiative" }, { name: "description", content: "Get in touch with NeuronBridge Initiative about student involvement, ideas, partnerships, and the developing UCLA community." }, { property: "og:title", content: "Contact Us | NeuronBridge Initiative" }, { property: "og:description", content: "Reach out to the NBI founding team with questions and ideas." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Contact });
function Contact() { const [pending, setPending] = useState(false); const [status, setStatus] = useState(""); const [error, setError] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; setPending(true); setStatus(""); setError(false); const form = event.currentTarget; const data = new FormData(form);
    const { error: insertError } = await supabase.from("contact_submissions").insert({ name: String(data.get("name") || "").trim(), email: String(data.get("email") || "").trim(), subject: String(data.get("subject") || "").trim(), message: String(data.get("message") || "").trim() });
    setPending(false); if (insertError) { setError(true); setStatus("We couldn't send your message right now. Please try again."); } else { form.reset(); setStatus("Thank you for reaching out. Your message has been received."); }
  }
  return <main><PageHead label="Contact" title="Let's start a conversation." description="Have an idea, a question, or an interest in collaborating? Send us a note—we'd love to hear from you." /><section className="section site-wrap form-layout"><div className="form-intro"><span className="eyebrow">Write to us</span><h2>We're listening.</h2><p>Whether you're a student, potential collaborator, mentor, or community partner, use this form to connect with the NBI founding team.</p><p className="small-note">Social channels will be shared here once official NBI accounts are available. We won't link to unconfirmed accounts.</p></div><form onSubmit={submit} className="form-fields"><div className="field"><label htmlFor="contact-name">Your name *</label><input id="contact-name" name="name" required minLength={2} maxLength={120} autoComplete="name" /></div><div className="field"><label htmlFor="contact-email">Email address *</label><input id="contact-email" name="email" type="email" required maxLength={254} autoComplete="email" /></div><div className="field full"><label htmlFor="contact-subject">Subject *</label><input id="contact-subject" name="subject" required minLength={2} maxLength={160} /></div><div className="field full"><label htmlFor="contact-message">Message *</label><textarea id="contact-message" name="message" required minLength={10} maxLength={5000} /></div><div className="field full"><Button type="submit" className="action-primary justify-self-start" disabled={pending}>{pending ? "Sending…" : "Send message"}<ArrowUpRight size={16} /></Button><p className="small-note">Your message is private and will only be used to respond to your inquiry.</p>{status && <p role="status" className={`form-status ${error ? "error" : ""}`}>{status}</p>}</div></form></section></main>;
}
