import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import brain from "@/assets/brain-engraving.jpg";
import neuron from "@/assets/neuron-engraving.jpg";
import { pillars, building } from "@/lib/site-content";
import { Callout, StatusNotice } from "@/components/page-parts";
export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "NeuronBridge Initiative | Neuroscience, Service & Community at UCLA" }, { name: "description", content: "Discover NeuronBridge Initiative, a developing UCLA student organization bringing neuroscience, service, neurodiversity outreach, mentorship, and community together." }, { property: "og:title", content: "NeuronBridge Initiative | UCLA" }, { property: "og:description", content: "A developing student community connecting neuroscience, service, and care at UCLA." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Index });
function Index() { return <main>
  <section className="hero"><div className="hero-copy"><p className="hero-org">NeuronBridge Initiative</p><span className="eyebrow">A developing UCLA student organization</span><h1 className="hero-title">Bridging neuroscience, medicine, <em>and community.</em></h1><p className="hero-text">A neuroscience-centered premed community at UCLA connecting students with service, clinical experiences, mentorship, neurodiversity outreach, professional development, and one another.</p><div className="hero-actions"><Link to="/join" className="action-primary">Become a Founding Member <ArrowUpRight size={16} /></Link><Link to="/about" className="action-text">Discover NBI <ArrowUpRight size={14} /></Link></div></div><div className="hero-visual"><img src={brain} alt="Vintage anatomical illustration of the human brain" width={1200} height={1504} /><div className="hero-stamp"><span>Fig. 01 — The mind in motion</span><span>NBI / UCLA</span></div></div></section>
  <div className="ticker"><div className="site-wrap ticker-inner"><span>Neuroscience</span><span>Service</span><span>Neurodiversity</span><span>Mentorship</span><span>Community</span></div></div>
  <section className="section statement site-wrap"><div><span className="eyebrow">A note on our mission</span></div><div><h2>More than neuroscience in the classroom.</h2><p>NeuronBridge Initiative exists to help students turn their interest in neuroscience and medicine into meaningful experience. Through service, clinical exposure, mentorship, neurodiversity outreach, professional development, and community, we give premed and neuroscience-minded students real ways to learn, contribute, and prepare for careers in healthcare.</p><Link to="/about" className="action-text">Read our story <ArrowUpRight size={14} /></Link></div></section>
  <section className="section pillars-preview"><div className="site-wrap"><div className="section-header"><div><span className="eyebrow">What guides us</span><h2 className="section-heading">Six pillars. One purpose.</h2></div><p className="section-intro">A connected approach to learning, serving, and growing together.</p></div><div className="pillar-grid">{pillars.map((p, i) => <div className="pillar-item" key={p.title}><span className="pillar-num">0{i + 1}</span><h3>{p.title}</h3><p>{p.text}</p></div>)}</div><div className="mt-8"><Link to="/pillars" className="action-text">Explore our pillars <ArrowUpRight size={14} /></Link></div></div></section>
  <section className="section site-wrap"><div className="section-header"><div><span className="eyebrow">What we're building</span><h2 className="section-heading">Experiences in development.</h2></div><p className="section-intro">Tangible opportunities NBI is actively working toward. Each is planned or in development as we grow.</p></div>{building.map((b, i) => <article className="list-row" key={b.title}><span className="list-row-index">0{i + 1}</span><div><h3>{b.title}</h3><p>{b.text}</p></div><span className="list-row-tag">{b.tag}</span></article>)}</section>
  <section className="feature-split"><div className="feature-image"><img src={neuron} alt="Vintage illustration of a branching neuron" width={1104} height={912} loading="lazy" /></div><div className="feature-copy"><span className="eyebrow">The founding chapter</span><h2>Be here at the beginning.</h2><p>NeuronBridge is being built from the ground up, which means our earliest members won't simply join an established organization—they'll help shape what it becomes. Founding members will have opportunities to contribute ideas, develop programs and traditions, serve our community, and grow into future leadership.</p><p className="founding-goal">Our goal: become a fully registered UCLA student organization by Winter 2027.</p><Link to="/join" className="action-text">Explore Founding Membership <ArrowUpRight size={14} /></Link></div></section>
  <section className="section-tight site-wrap"><StatusNotice /></section><Callout title="Your curiosity belongs here." label="Join our community" />
</main>; }
