import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { ArrowUpRight } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { PageHead, StatusNotice } from "@/components/page-parts";
export const Route = createFileRoute("/join")({ head: () => ({ meta: [{ title: "Join NBI & Founding Members | NeuronBridge Initiative" }, { name: "description", content: "Join the NeuronBridge Initiative interest list and express interest in becoming a founding member or future leader at UCLA." }, { property: "og:title", content: "Get Involved | NeuronBridge Initiative" }, { property: "og:description", content: "Join NBI's interest list and help shape a developing neuroscience community at UCLA." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Join });
const interestOptions = ["Neuroscience", "Premed & clinical", "Community service", "Neurodiversity outreach", "Mentorship", "Publications"];
function Join() {
  const [pending, setPending] = useState(false); const [status, setStatus] = useState(""); const [error, setError] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; setPending(true); setStatus(""); setError(false); const form = event.currentTarget; const data = new FormData(form);
    const { error: insertError } = await supabase.from("interest_submissions").insert({ name: String(data.get("name") || "").trim(), email: String(data.get("email") || "").trim(), study_year: String(data.get("study_year") || ""), interests: data.getAll("interests").map(String), founding_interest: data.get("founding_interest") === "on" });
    setPending(false); if (insertError) { setError(true); setStatus("We couldn't save your interest right now. Please try again."); } else { form.reset(); setStatus("Thank you for joining the interest list. We're glad you're here."); }
  }
  return <main><PageHead label="Get involved" title="Be part of the beginning." description="Whether you're drawn to neuroscience, service, healthcare, or the people you'll meet along the way, we'd love to hear from you." /><section className="section site-wrap form-layout"><div className="form-intro"><span className="eyebrow">The founding chapter</span><h2>Help shape what NBI becomes.</h2><p>We're inviting interested students to join our early community. If you'd like to help build NBI from the ground up—or explore future leadership as the organization develops—let us know below.</p><p>Joining the interest list is not a membership commitment. We'll share updates on meetings, projects, and opportunities when details are confirmed.</p><StatusNotice /></div><form onSubmit={submit} className="form-fields"><div className="field"><label htmlFor="join-name">Your name *</label><input id="join-name" name="name" required minLength={2} maxLength={120} autoComplete="name" placeholder="First and last name" /></div><div className="field"><label htmlFor="join-email">Email address *</label><input id="join-email" name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@example.com" /></div><div className="field full"><label htmlFor="join-year">Year of study</label><select id="join-year" name="study_year" defaultValue=""><option value="">Select a year (optional)</option><option>First year</option><option>Second year</option><option>Third year</option><option>Fourth year</option><option>Graduate student</option><option>Other</option></select></div><div className="field full"><span className="check-label">What interests you?</span><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{interestOptions.map(item => <label className="check-row" key={item}><input type="checkbox" name="interests" value={item} />{item}</label>)}</div></div><div className="field full"><label className="check-row"><input type="checkbox" name="founding_interest" /><span>I'm interested in becoming a founding member and exploring future leadership opportunities.</span></label></div><div className="field full"><Button type="submit" className="action-primary justify-self-start" disabled={pending}>{pending ? "Submitting…" : "Join the interest list"}<ArrowUpRight size={16} /></Button><p className="small-note">Your details are used to follow up about NBI and are not shown publicly.</p>{status && <p role="status" className={`form-status ${error ? "error" : ""}`}>{status}</p>}</div></form></section></main>;
}
