import { createFileRoute } from "@tanstack/react-router";
import { PageHead, Callout, StatusNotice } from "@/components/page-parts";
export const Route = createFileRoute("/neurodiversity-service")({ head: () => ({ meta: [{ title: "Neurodiversity & Service | NeuronBridge Initiative" }, { name: "description", content: "How NeuronBridge Initiative approaches neurodiversity outreach, community service, and philanthropy at UCLA." }, { property: "og:title", content: "Neurodiversity & Service | NeuronBridge Initiative" }, { property: "og:description", content: "NBI's developing neurodiversity outreach and service mission at UCLA." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Page });
const areas = [
  { title: "Neurodiversity education", text: "Workshops and accessible materials that build understanding of autism, ADHD, dyslexia, and other forms of neurodivergence.", tag: "In development" },
  { title: "Community outreach", text: "Outreach designed with—not just for—neurodivergent individuals, families, and the organizations that support them.", tag: "Planned" },
  { title: "Hands-on service", text: "Volunteering with local community partners as relationships are established.", tag: "Planned" },
  { title: "Philanthropy & fundraising", text: "Donation initiatives and fundraising for causes connected to brain health and neurodiversity.", tag: "Planned" },
];
function Page() { return <main><PageHead label="Our service mission" title="Neurodiversity & service." description="Service and neurodiversity outreach sit at the heart of NBI. We want students' knowledge of the brain to translate into respect, understanding, and real support for the communities around us." /><section className="section site-wrap">{areas.map((a, i) => <article className="list-row" key={a.title}><span className="list-row-index">0{i + 1}</span><div><h3>{a.title}</h3><p>{a.text}</p></div><span className="list-row-tag">{a.tag}</span></article>)}<div className="notice mt-12"><strong>Our approach.</strong> We aim to center the voices and needs of neurodivergent people and to partner with established community organizations. Specific partnerships will be announced only once confirmed.</div><div className="mt-8"><StatusNotice /></div></section><Callout title="Serve with purpose." /></main>; }
